### ISSUE TITLE
Android app should remove location updates when MainActivity is not visible

### ISSUE THREAD

**Issue by marcnause** [DaylightingSociety/WhereAreTheEyes#10]
The Android app does not remove the location update listener when the MainActivity is closed or moved to the background. The app must be killed to stop listening to location updates.

Location updates should be registered in Activity.onResume() and should be unregistered in Activity.onPause().

**Comment by milo-trujillo** [comment]
Whoops, you're quite right. This change *might* add a delay before pins are updated when the app is re-opened, but it's well worth it to save battery life / avoid leaking location data.

This will be fixed in the next release.

**Comment by guerda** [comment]
Do you need any help here? I can try to support you with that issue.

**Comment by milo-trujillo** [comment]
Yes, that would be great! We would love the help.

**Comment by guerda** [comment]
I created a PR for this change. I tested it and now the app stops requesting the location. It automatically resumes the location updates on resume. I haven't experienced any delay on resume.
