### ISSUE TITLE
Plugin for OsmAnd

### ISSUE THREAD

**Issue by PanderMusubi** [DaylightingSociety/WhereAreTheEyes#11]
I find OsmAnd to be much more precise in pinpointing my location. It is very annoying that OsmAnd tells me exactly where I am and WhereAreTheEyes is 70 meters off. I would like to suggest to transform this app into a plugin for OsmAnd. Advantages are that much of the map stuff can be directly used from OsmAnd and does not need to be maintained anymore. Only focus is on the adding, removing, conforming and deleting of camera's.

**Comment by milo-trujillo** [comment]
Hmm, I'm not sure where the improved accuracy comes from. We use the highest location accuracy provided by Android and iOS, and are using OSM to render your location. I would love to find out, I've been frustrated by the lack of accuracy at times, too. 

We have no intention to turn this app into an OsmAnd plugin. One of the advantages of *Where are the Eyes* is its extreme simplicity, so while OsmAnd is a great tool with larger capabilities, we don't think combining with it would benefit most of our intended audience. If someone else wants to write a plugin for OsmAnd against our API then I'm all for it.

**Comment by PanderMusubi** [comment]
I have no idea why but OSM is way more acurate. Obviously, this app is not using the higest available location. Please rename to 'improve acuracy to level of osmand' and reopen this issue as this is a dealbreaker for me and many others.

**Comment by PanderMusubi** [comment]
OsmAnd might use additional resources such as:
* https://f-droid.org/repository/browse/?fdfilter=location&fdid=org.gfd.gsmlocation
* https://f-droid.org/repository/browse/?fdfilter=location&fdid=org.fitchfamily.android.gsmlocation
* https://f-droid.org/repository/browse/?fdfilter=location&fdid=org.fitchfamily.android.wifi_backend
* https://f-droid.org/repository/browse/?fdfilter=nlp&fdid=com.google.android.gms
* https://f-droid.org/repository/browse/?fdfilter=nlp&fdid=org.microg.nlp

and/or some additional improvement on location from recent acceleration or movement. Hence my proposal. If it is better and hard to obtain, better to use it directly.

**Comment by PanderMusubi** [comment]
OsmAnd has also direction or orientation, that is the way you are facing or looking. Would that involve higher and quicker accuracy?

**Comment by milo-trujillo** [comment]
No, orientation is based on the compass, not GPS or other location data.
