### ISSUE TITLE
Button for my location

### ISSUE THREAD

**Issue by PanderMusubi** [DaylightingSociety/WhereAreTheEyes#17]
Please add a button to center on my location and go to default zoom level.

**Comment by milo-trujillo** [comment]
Where would the button go, and what would it look like? I like the idea, provided it can be integrated cleanly into the existing UI.

**Comment by PanderMusubi** [comment]
It could go in the botton row of buttons. Perhaps the help can move to the upper part of the screen as you don't use that often.

**Comment by milo-trujillo** [comment]
This is a good idea, and was only cut from v1.3.0 because it wasn't implemented on both platforms in time and we'd prefer to make the user experience as similar as possible on all devices. Expect to see it soon.

**Comment by milo-trujillo** [comment]
This is now implemented on both platforms in 1.4. Closing the issue; the feature is included in the upcoming release.
