### ISSUE TITLE
Host Open-Sans Locally

### ISSUE THREAD

**Issue by YeahSPARTAA** [DaylightingSociety/WhereAreTheEyes#2]
Whenever someone visits https://eyes.daylightingsociety.org a request to googleapis.com is made:

`<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,300,800,700' rel='stylesheet' type='text/css'>`

Suggesting to host it locally to prevent Google from tracking visitors.

Open-Sans download zip file:

https://fonts.google.com/download?family=Open%20Sans

**Comment by milo-trujillo** [comment]
Oof, I hadn't considered that for tracking at all, that was a nasty oversight on my part. I will correct this as soon as I get a chance, thank you.

**Comment by milo-trujillo** [comment]
We are now hosting Open-Sans locally. Thank you for drawing this to our attention.
