### ISSUE TITLE
Material Design colors

### ISSUE THREAD

**Issue by PanderMusubi** [DaylightingSociety/WhereAreTheEyes#20]
Use only Material Design colors to keep it an integrated user experience with the device where users expect certain colors.

**Comment by milo-trujillo** [comment]
Where are we not following this practice, and on which platform? More information would be appreciated.

**Comment by PanderMusubi** [comment]
Android

**Comment by milo-trujillo** [comment]
The user can now choose the color-scheme of the map from a number of themes. We are not making changes in color to the Android black-and-white UI at this time, but will reconsider if a lot of the community thinks it needs improvement.
