### ISSUE TITLE
Material Design launcher icon

### ISSUE THREAD

**Issue by PanderMusubi** [DaylightingSociety/WhereAreTheEyes#21]
Please use a launcher icon in SVG based upon Material Design icons and colors. For this, special websites exist to create a launcher icon without having to open graphical design software.

**Comment by milo-trujillo** [comment]
We will be maintaining our current launcher icon for the foreseeable future. We'll switch to SVG if it's possible, I'll confer with our artist and see if there's a vector form of the original.
