### ISSUE TITLE
Increase rotate threshold

### ISSUE THREAD

**Issue by PanderMusubi** [DaylightingSociety/WhereAreTheEyes#28]
Please, increase the threshold for the rotation of the map. The map starts rotating to soon. Implement something similar as in OsmAnd so the user has to do a more explicitely action to start rotating. Benefit is that rotation is not started too quickly with a normal zoom or pan action.

**Comment by milo-trujillo** [comment]
As far as I know rotation and rendering is implemented by MapBox, and is not adjustable from the API. I can enable and disable rotation, and even make rotation follow the compass (which may be a useful feature, along with panning to stay centered on the user), but can't adjust how sensitive rotation is. If you can find me the API calls to do this I'll re-open the issue.

**Comment by PanderMusubi** [comment]
Are you using this? https://github.com/mapbox/mapbox.js/

**Comment by milo-trujillo** [comment]
No. We're using the native Mapbox for iOS and Android: https://github.com/mapbox/mapbox-gl-native

**Comment by PanderMusubi** [comment]
There have a number of issues on this. Some asking for the opposite. Recently, some pull requests have been merged regarding this. Please, have a look at recent and older activity in:
* https://github.com/mapbox/mapbox-gl-native/issues/7666
* https://github.com/mapbox/mapbox-gl-native/pull/7299
* https://github.com/mapbox/mapbox-gl-native/issues/7058
* https://github.com/mapbox/mapbox-gl-native/issues/6870
* https://github.com/mapbox/mapbox-gl-native/issues/6562

As you are working on the development, you have more insight if the threshold for rotation is going to be configurable or not. Otherwise, could you create a future request there as you know exactly which API calls this concerns.

**Comment by milo-trujillo** [comment]
Thank you for finding the relevant issues. 6562 seems particularly appropriate. One last question then - are you seeing this behavior on Android, or iOS? If you're seeing it on Android then I'll try to get them to broaden 6562 to include both platforms.

It sounds like this is mostly a limitation of Mapbox: If they fix it on their end then this will no longer be a problem for *Where are the Eyes*. If they make the rotation threshold configurable then we'll re-open this issue and fix it.

**Comment by PanderMusubi** [comment]
Android. No idea about iOS. Thanks.
