### ISSUE TITLE
No camera on the map

### ISSUE THREAD

**Issue by stemy2** [DaylightingSociety/WhereAreTheEyes#40]
Hello,

I don't see any camera on the map, even those i placed myself. I don't even see the cameras that i saw in the past on the app. That makes the app totally useless.

**Comment by milo-trujillo** [comment]
I can't reproduce this, the app seems to be working fine for me. Have you given it location access and have GPS turned on? Also, are you on Android, or iOS?

**Comment by stemy2** [comment]
Yes, and it shows me where i am. But not any camera.

**Comment by milo-trujillo** [comment]
Running the API calls by hand shows that everything is fine on the server end. Can you get any debugging output from your device? Have you tried restarting the app?

**Comment by milo-trujillo** [comment]
Confirmed that I'm seeing proper behavior on Android and iOS. I'm closing this issue as "cannot reproduce" unless I get more information from other users.
