### ISSUE TITLE
F-Droid version outdated

### ISSUE THREAD

**Issue by rugk** [DaylightingSociety/WhereAreTheEyes#41]
F-Droid still has v1.2.1, but you released v1.3.0 some time ago.

**Comment by milo-trujillo** [comment]
I think this may be a problem on F-Droid's end - [their own repository says we're at version 1.3.0](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.daylightingsociety.wherearetheeyes.txt). Alternatively, something got screwed up in that config file. Can someone more familiar with F-Droid shed some light on this?

Thank you for bringing this to our attention, I had no idea the latest version wasn't downloadable.

**Comment by rugk** [comment]
As you said in https://github.com/DaylightingSociety/WhereAreTheEyes/issues/42#issuecomment-325844339: 
> and we aren't using GitHub tags for F-Droid anyway

Now I am curious. How do you do it?

**Comment by milo-trujillo** [comment]
F-Droid reads the version number from our [Android package manifest](https://github.com/DaylightingSociety/WhereAreTheEyes/blob/master/Android/app/build.gradle#L10-L11). This is the `RepoManifest` option in the [F-Droid metadata](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/org.daylightingsociety.wherearetheeyes.txt#L35).

**Comment by rugk** [comment]
Ah, thanks for your info.

**Comment by hex-m** [comment]
I created an issue [over there](https://gitlab.com/fdroid/fdroiddata/issues/895).

**Comment by hex-m** [comment]
I think I understood the problem now. [Auto Update](https://f-droid.org/docs/Build_Metadata_Reference/#Auto-Update-Mode) is disabled for this application so a new release means someone has to change the f-droid metadata manually. Is there a special reason why auto update is not used? It would avoid the release delay for future versions.

**Comment by Bubu** [comment]
Auto Update cannot be enabled because this project doesn't use tags. Please consider tagging releases.

**Comment by milo-trujillo** [comment]
Is Auto Update incompatible with RepoManifest [Update Check Mode](https://f-droid.org/docs/Build_Metadata_Reference/#Update-Check-Mode)? My understanding is we can, and previously *were*, auto-updating F-Droid by putting a new version number in the Android manifest.

The auto-updating got disabled after v1.2.1, when I screwed up and pushed a broken build to master, and someone patched the F-Droid config to explicitly point towards the correct version. If that's the case, we should be able to re-enable auto-updates and everything will run fine now.

**Comment by Bubu** [comment]
AutoUpdateMode was always None on F-Droid, UpdateCheckMode is enabled and detects new versions. But AFAIK auto-generating new build entries only works with tags.

**Comment by ghost** [comment]
Latest version is on it now
https://f-droid.org/packages/org.daylightingsociety.wherearetheeyes/

**Comment by milo-trujillo** [comment]
Thanks everyone! Closing this issue for now since the latest release *is* available on F-Droid, but we'll get automatic updates working starting with the next update.
