### ISSUE TITLE
Should be able to remove my own registrations

### ISSUE THREAD

**Issue by senorwafflez** [DaylightingSociety/WhereAreTheEyes#6]
If I marked a camera by mistake for some reason, I should be able to edit/delete the registration.
Confirmations aren't really a security against mistakes. Besides, it obviously doesn't always work.

The three first times I tested the app, it didn't ask for confirmation when pinning a camera.
Even though the switch for confirmations was on.
Should the switch be off for some reason, it is quite possible to mark cameras by mistake.

**Comment by alcharkov** [comment]
Not really possible to mark by mistake, there is confirm dialog after the mark

**Comment by milo-trujillo** [comment]
We agree. We're still working on implementing 'undo', it's a little bit complicated to build while preventing abuse and protecting everyone's anonymity, but it's definitely possible.

**Comment by milo-trujillo** [comment]
Undo is now implemented in version 1.2. To use it you:
- Tap on a pin
- Press the info button
- Press "Remove"

Let us know if there's a way we can make the process more intuitive, but it is now working.
