### ISSUE TITLE
Users should be allowed to mark camera location in GPS range, if GPS is inaccurate

### ISSUE THREAD

**Issue by khushman1** [DaylightingSociety/WhereAreTheEyes#7]
We often have GPS issues, where the accuracy goes >250m, showing the blue dot on an incorrect location. Instead of directly adding the marker at my current location, there should be an option to allow the user to click on his exact location.

P.S. I don't know if this should be a new issue, but a loading indicator when we submit markers would be great to know our request is being processes.

**Comment by BoBeR182** [comment]
Also for camera's behind fences or one's you cannot be underneath to add.

**Comment by milo-trujillo** [comment]
The problem with allowing user selection of location is that users tend to have much lower precision than the GPS of the device. GPS doesn't work indoors or if you can't get physically close to the camera though, so perhaps it's a worthwhile trade-off.

**Comment by khushman1** [comment]
@milo-trujillo Agreed. But you don't give the user an option of laying a marker anywhere on the map, just inside the inaccuracy circle of the GPS data, so that there is a good trade-off between actual location, and user input. Or maybe a slightly larger circle around the user's GPS data?

**Comment by senorwafflez** [comment]
What about also being able to tag cameras as indoors/underground?

**Comment by milo-trujillo** [comment]
> give the user an option of laying a marker... inside the inaccuracy circle of the GPS
> 
> tag cameras as indoors/underground

These are both excellent ideas. Hopefully the map will _show_ a camera as being indoors, but being able to mark underground / above ground still adds a lot of valuable data for multi-story structures.

Integrating this into the UI could get a little complicated. For marking existing cameras as above/below ground we could add a button to the little panel that appears when you press a camera.

For marking cameras not at your current location... Maybe you could drag from the eye button to where you see the camera? I'm hesitant to make tapping the map mark a camera, people will likely do that by accident while trying to navigate.

**Comment by milo-trujillo** [comment]
@khushman1

> P.S. I don't know if this should be a new issue, but a loading indicator when we submit markers would be great to know our request is being processes.

We added haptic feedback to the latest release, so it makes a *buzz* when you mark / unmark a camera, letting you know the request is underway. Would a visual indicator still be appreciated?

**Comment by mb06cs** [comment]
@milo-trujillo Yep, the buzzing feedback is interesting but a visual message would be great. For example, we all have a lot of apps buzzing at all time on our phone.

Also, concerning the possibility of adding a marker outside the GPS range, this can be a great improvement for accuracy. My GPS is sometimes very unacurrate, but I know how to move throught streets to find out how I can be in range (thanks Ingress for that...).

Great job already

M, Lyon, France.

**Comment by milo-trujillo** [comment]
This issue has been replaced by #51. Same idea, by the specifics are hammered out succinctly there instead of across a conversation.
